algoritmo "soma-de-dois-numeros"
// Função : Le dois numeros do teclado e mostra a soma deles.
// Autor : Nicolas França
// Data : 3/23/2016

// Seção de Declarações
var
   a, b, soma: real

inicio
// Seção de Comandos
   escreva("Digite o primeiro número: ")
   leia(a)
   escreva("Digite o segundo número: ")
   leia(b)
   soma <- a + b
   escreva("A soma de", a, " +", b, " é igual a", soma)
fimalgoritmo
